# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Set up Toolchain
      shell: bash
      run: |
        mkdir -p $HOME/.m2 \
        && cat << EOF > $HOME/.m2/toolchains.xml
        <?xml version="1.0" encoding="UTF8"?>
        <toolchains>
          <toolchain>
            <type>jdk</type>
              <provides>
                <version>11</version>
                <vendor>Temurin</vendor>
              </provides>
              <configuration>
                <jdkHome>${{ env.JAVA_HOME }}</jdkHome>
              </configuration>
          </toolchain>
        </toolchains>
        EOF

    - name: Build with Maven
      run: mvn -B package --file pom.xml


    - name: Upload asset for repository
      uses: icrawl/action-artifact@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: "**/target/*.amp"
